cache:
  bundler: true
  yarn: true
  directories:
    - ./bin/setup
  services:
    - elasticsearch
before_script:
  - sleep 5
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create RAILS_ENV=test # database user by default is `travis`
  - bundle exec rake db:migrate RAILS_ENV=test
language: ruby
rvm:
  - 2.5.3
script:
  - bundle exec rspec
